<script setup lang="ts">
interface LedgerRow { id: string; entryDate: string; voucherNo: string; purchaseNo: string | null; particulars: string | null; debit: string; credit: string; paymentMode: string | null; referenceNo: string | null; dueDate: string | null; status: string; buyerName: string | null; remarks: string | null; enteredByName: string | null; approvedByName: string | null; rating: string | null }
interface SupplierDetail { id: string; code: string; name: string; outstandingBalance: number; ledger: LedgerRow[] }
const route = useRoute(); const { data } = await useFetch<SupplierDetail>(`/api/suppliers/${route.params.id}`)
function fmt(value: string | number) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value)) }
const runningLedger = computed(() => { if (!data.value) return []; let balance = 0; return data.value.ledger.map((row) => { balance += Number(row.credit) - Number(row.debit); return { ...row, runningBalance: balance } }) })
</script>
<template><div v-if="data"><NuxtLink to="/suppliers">← Back to Supplier Master</NuxtLink><div style="display:flex;justify-content:space-between;align-items:end;margin:12px 0 20px;"><div><h1 style="font-size:20px;margin:0;">Supplier Ledger</h1><p style="color:var(--color-text-muted);margin:4px 0 0;">{{ data.name }} · {{ data.code }}</p></div><div class="card" style="margin:0;padding:10px 14px;"><div style="font-size:12px;color:var(--color-text-muted);">Running Balance</div><strong class="kpi-value">{{ fmt(data.outstandingBalance) }}</strong></div></div><div style="overflow-x:auto;"><table style="width:100%;min-width:1950px;border-collapse:collapse;"><thead><tr><th>Date</th><th>Voucher No</th><th>Purchase No</th><th>Supplier ID</th><th>Supplier Name</th><th>Particulars</th><th>Debit - Payments (Rs)</th><th>Credit - Purchases (Rs)</th><th>Running Balance (Rs)</th><th>Payment Mode</th><th>Reference No</th><th>Due Date</th><th>Status</th><th>Buyer</th><th>Remarks</th><th>Entered By</th><th>Approved By</th><th>Rating</th></tr></thead><tbody><tr v-for="row in runningLedger" :key="row.id"><td>{{ row.entryDate }}</td><td>{{ row.voucherNo }}</td><td>{{ row.purchaseNo || '—' }}</td><td>{{ data.code }}</td><td>{{ data.name }}</td><td>{{ row.particulars || '—' }}</td><td>{{ Number(row.debit) > 0 ? fmt(row.debit) : '—' }}</td><td>{{ Number(row.credit) > 0 ? fmt(row.credit) : '—' }}</td><td>{{ fmt(row.runningBalance) }}</td><td>{{ row.paymentMode || '—' }}</td><td>{{ row.referenceNo || '—' }}</td><td>{{ row.dueDate || '—' }}</td><td>{{ row.status }}</td><td>{{ row.buyerName || '—' }}</td><td>{{ row.remarks || '—' }}</td><td>{{ row.enteredByName || '—' }}</td><td>{{ row.approvedByName || '—' }}</td><td>{{ row.rating || '—' }}</td></tr></tbody></table></div></div></template>
<style scoped>th,td{padding:8px;text-align:left;white-space:nowrap;border-bottom:1px solid var(--color-border)}th{font-size:12px}</style>
