<script setup lang="ts">
interface Supplier { id:string; code:string; name:string; company:string|null; contactPerson:string|null; phone:string|null; email:string|null; gstin:string|null; address:string|null; city:string|null; state:string|null; pinCode:string|null; openingBalance:string; creditTermsDays:string|null; creditLimit:string|null; status:string; createdAt:string; lastPurchase:string|null; remarks:string|null; supplierType:string; rating:string|null }
const { data:list, refresh } = await useFetch<Supplier[]>('/api/suppliers')
const editing = ref<Supplier|null>(null)
const showForm = ref(false)
const error = ref('')
const form = reactive({ name:'', company:'', contactPerson:'', phone:'', email:'', gstin:'', address:'', city:'', state:'', pinCode:'', openingBalance:0, creditTermsDays:0, creditLimit:0, status:'active', supplierType:'regular', rating:0, remarks:'' })
const textFields = ['name','company','contactPerson','phone','email','gstin','address','city','state','pinCode'] as const

function resetForm() { Object.assign(form, { name:'', company:'', contactPerson:'', phone:'', email:'', gstin:'', address:'', city:'', state:'', pinCode:'', openingBalance:0, creditTermsDays:0, creditLimit:0, status:'active', supplierType:'regular', rating:0, remarks:'' }) }
function startNew() { editing.value = null; resetForm(); error.value = ''; showForm.value = true }
function cancel() { editing.value = null; showForm.value = false; error.value = '' }
function edit(row: Supplier) { editing.value = row; showForm.value = true; error.value = ''; Object.assign(form, { name:row.name, company:row.company||'', contactPerson:row.contactPerson||'', phone:row.phone||'', email:row.email||'', gstin:row.gstin||'', address:row.address||'', city:row.city||'', state:row.state||'', pinCode:row.pinCode||'', openingBalance:Number(row.openingBalance||0), creditTermsDays:Number(row.creditTermsDays||0), creditLimit:Number(row.creditLimit||0), status:row.status, supplierType:row.supplierType, rating:Number(row.rating||0), remarks:row.remarks||'' }) }
function optional(value: string) { return value.trim() || undefined }
async function save() {
  error.value = ''
  try {
    const body = { ...form, name: form.name.trim(), company:optional(form.company), contactPerson:optional(form.contactPerson), phone:optional(form.phone), email:optional(form.email), gstin:optional(form.gstin), address:optional(form.address), city:optional(form.city), state:optional(form.state), pinCode:optional(form.pinCode), supplierType:form.supplierType.trim(), remarks:optional(form.remarks) }
    if (editing.value) {
      const { openingBalance: _openingBalance, ...updateBody } = body
      await $fetch(`/api/suppliers/${editing.value.id}`, { method:'PATCH', body:updateBody })
    } else {
      await $fetch('/api/suppliers', { method:'POST', body })
    }
    cancel()
    await refresh()
  } catch (e:any) { error.value = e?.data?.statusMessage || 'Could not save supplier' }
}
</script>
<template><main><div class="heading"><div><h1>Supplier Master</h1><p>One permanent record per supplier. Supplier ID and opening balance are controlled by the system.</p></div><button type="button" @click="showForm ? cancel() : startNew()">{{ showForm ? 'Cancel' : '+ New Supplier' }}</button></div><form v-if="showForm" class="card form" @submit.prevent="save"><label v-for="key in textFields" :key="key">{{ key === 'phone' ? 'Mobile' : key }}<input v-model="form[key]" :required="key === 'name'"></label><label>Opening Balance (Rs)<input v-model.number="form.openingBalance" type="number" min="0" :disabled="!!editing"></label><label>Credit Terms (days)<input v-model.number="form.creditTermsDays" type="number" min="0"></label><label>Credit Limit (Rs)<input v-model.number="form.creditLimit" type="number" min="0"></label><label>Supplier Type<input v-model="form.supplierType" required></label><label>Rating<input v-model.number="form.rating" type="number" min="0" max="5" step="0.5"></label><label>Status<select v-model="form.status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label class="wide">Remarks<textarea v-model="form.remarks" maxlength="1000"></textarea></label><span class="error">{{error}}</span><div class="actions"><button>Save Supplier</button><button type="button" @click="cancel">Cancel</button></div></form><div class="card table"><table><thead><tr><th>Supplier ID</th><th>Supplier Name</th><th>Company</th><th>Mobile</th><th>Email</th><th>GSTIN</th><th>Address</th><th>City</th><th>State</th><th>PIN Code</th><th>Opening Balance (Rs)</th><th>Credit Terms</th><th>Status</th><th>Created On</th><th>Last Purchase</th><th>Remarks</th><th>Contact Person</th><th>Supplier Type</th><th>Credit Limit (Rs)</th><th>Action</th></tr></thead><tbody><tr v-for="row in list||[]" :key="row.id"><td>{{row.code}}</td><td>{{row.name}}</td><td>{{row.company||'—'}}</td><td>{{row.phone||'—'}}</td><td>{{row.email||'—'}}</td><td>{{row.gstin||'—'}}</td><td>{{row.address||'—'}}</td><td>{{row.city||'—'}}</td><td>{{row.state||'—'}}</td><td>{{row.pinCode||'—'}}</td><td>{{row.openingBalance}}</td><td>{{row.creditTermsDays||'—'}}</td><td>{{row.status}}</td><td>{{row.createdAt.slice(0,10)}}</td><td>{{row.lastPurchase||'—'}}</td><td>{{row.remarks||'—'}}</td><td>{{row.contactPerson||'—'}}</td><td>{{row.supplierType}}</td><td>{{row.creditLimit||'—'}}</td><td><button type="button" @click="edit(row)">Edit</button></td></tr></tbody></table></div></main></template>
<style scoped>main{padding:4px}.heading{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}h1{font-size:20px;margin-bottom:4px}.heading p{margin:0;color:var(--color-muted);font-size:13px}.form{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}label{font-size:12px}input,select,textarea{display:block;width:100%;padding:8px;margin-top:4px;border:1px solid var(--color-border);border-radius:5px;background:var(--color-surface)}textarea{min-height:70px;resize:vertical}.wide{grid-column:span 2}.actions{display:flex;align-items:end;gap:8px}.actions button:last-child{background:var(--color-muted)}button{padding:8px 12px;background:var(--color-accent);color:#fff;border:0;border-radius:5px;cursor:pointer}.error{color:var(--color-danger);grid-column:1/-1}.table{overflow:auto;margin-top:16px}table{min-width:2050px;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid var(--color-border);white-space:nowrap}th{font-size:12px}</style>
<style scoped>main{padding:4px}h1{font-size:20px}.form{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}label{font-size:12px}input,select{display:block;width:100%;padding:8px;margin-top:4px;border:1px solid var(--color-border);border-radius:5px}button{padding:8px 12px;background:var(--color-accent);color:#fff;border:0;border-radius:5px;cursor:pointer}.error{color:var(--color-danger)}.table{overflow:auto;margin-top:16px}table{min-width:2050px;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid var(--color-border);white-space:nowrap}th{font-size:12px}</style>
