<script setup lang="ts">
interface Supplier { id:string; code:string; name:string; company:string|null; phone:string|null; status:string; openingBalance:string; creditLimit:string|null }
const { data: suppliers, refresh } = await useFetch<Supplier[]>('/api/suppliers')
const editing = ref<Supplier|null>(null)
const form = reactive({ name:'', company:'', phone:'', status:'active', creditLimit:0 })
function edit(row: Supplier) { editing.value=row; Object.assign(form,{name:row.name,company:row.company||'',phone:row.phone||'',status:row.status,creditLimit:Number(row.creditLimit||0)}) }
async function save() { if (!editing.value) return; await $fetch(`/api/suppliers/${editing.value.id}`,{method:'PATCH',body:form}); editing.value=null; await refresh() }
</script>
<template><div><h1>Supplier Master</h1><form v-if="editing" class="card" @submit.prevent="save"><input v-model="form.name" required><input v-model="form.company"><input v-model="form.phone"><input v-model.number="form.creditLimit" type="number" min="0"><select v-model="form.status"><option>active</option><option>inactive</option></select><button>Save Supplier</button><button type="button" @click="editing=null">Cancel</button></form><div class="card" style="overflow:auto"><table><thead><tr><th>Supplier ID</th><th>Name</th><th>Company</th><th>Mobile</th><th>Opening Balance</th><th>Credit Limit</th><th>Status</th><th>Action</th></tr></thead><tbody><tr v-for="row in suppliers||[]" :key="row.id"><td>{{row.code}}</td><td>{{row.name}}</td><td>{{row.company||'—'}}</td><td>{{row.phone||'—'}}</td><td>{{row.openingBalance}}</td><td>{{row.creditLimit||'—'}}</td><td>{{row.status}}</td><td><button @click="edit(row)">Edit</button><NuxtLink :to="`/suppliers/${row.id}`">Ledger</NuxtLink></td></tr></tbody></table></div></div></template>
