<script setup lang="ts">
interface Customer { id: string; code: string; name: string }
interface LedgerRow { id: string; entryDate: string; voucherNo: string; invoiceNo: string | null; particulars: string | null; debit: string; credit: string; paymentMode: string | null; referenceNo: string | null; dueDate: string | null; status: string; salespersonName: string | null; remarks: string | null; enteredByName: string | null; approvedByName: string | null }
interface CustomerDetail { id: string; code: string; name: string; outstandingBalance: number; ledger: LedgerRow[] }
const { data: customers } = await useFetch<Customer[]>('/api/customers')
const selectedCustomerId = ref('')
const detail = ref<CustomerDetail | null>(null)
const loading = ref(false)
const submitting = ref(false)
const message = ref('')
const error = ref('')
const form = reactive({ entryDate: new Date().toISOString().slice(0, 10), amount: 0, paymentMode: 'cash', referenceNo: '', remarks: '' })
watch(customers, (rows) => { if (!selectedCustomerId.value && rows?.[0]) selectedCustomerId.value = rows[0].id }, { immediate: true })
watch(selectedCustomerId, async (id) => { if (!id) { detail.value = null; return }; loading.value = true; try { detail.value = await $fetch<CustomerDetail>(`/api/customers/${id}`) } finally { loading.value = false } })
function fmt(value: string | number) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(Number(value)) }
const runningLedger = computed(() => { let balance = 0; return (detail.value?.ledger || []).map((row) => { balance += Number(row.debit) - Number(row.credit); return { ...row, runningBalance: balance } }) })
async function postReceipt() { if (!selectedCustomerId.value) return; submitting.value = true; message.value = ''; error.value = ''; try { const result = await $fetch<{ voucherNo: string }>('/api/party-ledger/payments', { method: 'POST', body: { partyType: 'customer', partyId: selectedCustomerId.value, ...form } }); message.value = `${result.voucherNo} posted successfully.`; form.amount = 0; form.referenceNo = ''; form.remarks = ''; detail.value = await $fetch<CustomerDetail>(`/api/customers/${selectedCustomerId.value}`) } catch (e: any) { error.value = e?.data?.statusMessage || 'Could not post customer receipt.' } finally { submitting.value = false } }
</script>
<template>
  <main><div class="heading"><div><h1>Customer Ledger</h1><p>Accounts receivable ledger linked to the Customer Master. Posted rows are append-only.</p></div><NuxtLink class="link-button" to="/customers">Customer Master</NuxtLink></div>
    <section class="toolbar card"><label>Customer<select v-model="selectedCustomerId"><option v-for="customer in customers || []" :key="customer.id" :value="customer.id">{{ customer.name }} — {{ customer.code }}</option></select></label><div v-if="detail" class="balance"><span>Running Balance</span><strong>{{ fmt(detail.outstandingBalance) }}</strong></div></section>
    <form v-if="detail" class="card receipt-form" @submit.prevent="postReceipt"><h2>Record Customer Receipt</h2><label>Date<input v-model="form.entryDate" type="date" required></label><label>Amount (Rs)<input v-model.number="form.amount" type="number" min="0.01" step="0.01" required></label><label>Payment Mode<select v-model="form.paymentMode"><option value="cash">Cash</option><option value="upi">UPI</option><option value="bank">Bank</option><option value="cheque">Cheque</option></select></label><label>Reference No<input v-model="form.referenceNo" maxlength="100"></label><label class="wide">Remarks<textarea v-model="form.remarks" maxlength="1000"></textarea></label><div class="form-actions"><span v-if="message" class="success">{{ message }}</span><span v-if="error" class="error">{{ error }}</span><button :disabled="submitting">{{ submitting ? 'Posting…' : 'Post Receipt' }}</button></div></form>
    <div v-if="loading" class="card">Loading ledger…</div><div v-else-if="detail" class="card table"><table><thead><tr><th>Date</th><th>Voucher No</th><th>Invoice No</th><th>Customer ID</th><th>Customer Name</th><th>Particulars</th><th>Debit - Owes (Rs)</th><th>Credit - Paid (Rs)</th><th>Running Balance (Rs)</th><th>Payment Mode</th><th>Reference No</th><th>Due Date</th><th>Status</th><th>Salesperson</th><th>Remarks</th><th>Entered By</th><th>Approved By</th></tr></thead><tbody><tr v-for="row in runningLedger" :key="row.id"><td>{{ row.entryDate }}</td><td>{{ row.voucherNo }}</td><td>{{ row.invoiceNo || '—' }}</td><td>{{ detail.code }}</td><td>{{ detail.name }}</td><td>{{ row.particulars || '—' }}</td><td>{{ Number(row.debit) ? fmt(row.debit) : '—' }}</td><td>{{ Number(row.credit) ? fmt(row.credit) : '—' }}</td><td>{{ fmt(row.runningBalance) }}</td><td>{{ row.paymentMode || '—' }}</td><td>{{ row.referenceNo || '—' }}</td><td>{{ row.dueDate || '—' }}</td><td>{{ row.status }}</td><td>{{ row.salespersonName || '—' }}</td><td>{{ row.remarks || '—' }}</td><td>{{ row.enteredByName || '—' }}</td><td>{{ row.approvedByName || '—' }}</td></tr><tr v-if="!runningLedger.length"><td colspan="17" class="empty">No ledger entries for this customer.</td></tr></tbody></table></div>
  </main>
</template>
<style scoped>main{max-width:100%}.heading{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}h1{font-size:20px;margin:0 0 4px}.heading p{margin:0;color:var(--color-text-muted);font-size:13px}.link-button,button{display:inline-block;padding:8px 12px;background:var(--color-accent);color:#fff;border:0;border-radius:5px;text-decoration:none;cursor:pointer}.toolbar{display:flex;align-items:end;gap:24px;margin-top:16px}.toolbar label{width:360px}label{font-size:12px}input,select,textarea{display:block;width:100%;padding:8px;margin-top:4px;border:1px solid var(--color-border);border-radius:5px;background:var(--color-surface)}.balance{margin-left:auto}.balance span{display:block;font-size:12px;color:var(--color-text-muted)}.balance strong{font-size:20px}.receipt-form{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.receipt-form h2{grid-column:1/-1;font-size:15px;margin:0}.wide{grid-column:span 2}.form-actions{grid-column:1/-1;display:flex;align-items:center;gap:12px}.success{color:var(--color-accent)}.error{color:var(--color-danger)}.table{overflow:auto;margin-top:16px}table{min-width:1900px;width:100%;border-collapse:collapse}th,td{padding:8px;text-align:left;white-space:nowrap;border-bottom:1px solid var(--color-border)}th{font-size:12px}.empty{text-align:center;padding:24px;color:var(--color-text-muted)}</style>
