<script setup lang="ts">
interface Account { code:string; name:string; type:string }
interface JournalRow { id:string; entryDate:string; accountHead:string; accountCode:string; debit:string; credit:string; particulars:string|null; reference:string|null; posted:string; enteredBy:string|null; approvedBy:string|null; remarks:string|null; createdAt:string }
const { data: accounts } = await useFetch<Account[]>('/api/accounts')
const { data: rows, refresh } = await useFetch<JournalRow[]>('/api/journal')
const submitting = ref(false)
const message = ref('')
const error = ref('')
const form = reactive({ entryDate:new Date().toISOString().slice(0,10), voucherNo:'', debitAccountCode:'', creditAccountCode:'', particulars:'', amount:0, reference:'', remarks:'' })
const accountOptions = computed(() => accounts.value || [])
function accountLabel(code:string) { const account = accountOptions.value.find((item) => item.code === code); return account ? `${account.name} (${account.code})` : code }
function journalNo(reference:string) { return `JNL-${reference.slice(0, 8).toUpperCase()}` }
function fmt(value:string) { return new Intl.NumberFormat('en-IN', { style:'currency', currency:'INR', maximumFractionDigits:2 }).format(Number(value)) }
async function submit() {
  submitting.value = true; message.value = ''; error.value = ''
  try { const result = await $fetch<{ journalNo:string }>('/api/journal', { method:'POST', body:form }); message.value = `${result.journalNo} posted successfully.`; Object.assign(form, { voucherNo:'', particulars:'', amount:0, reference:'', remarks:'' }); await refresh() } catch (e:any) { error.value = e?.data?.statusMessage || 'Could not post journal entry.' } finally { submitting.value = false }
}
</script>
<template>
  <main><div class="heading"><div><h1>Journal</h1><p>Optional double-entry journal. Every posting must balance before it reaches the General Ledger.</p></div><NuxtLink class="link-button" to="/admin/ledger-entries">Ledger Audit</NuxtLink></div>
    <form class="card form" @submit.prevent="submit"><h2>Post Journal Entry</h2><label>Date<input v-model="form.entryDate" type="date" required></label><label>Voucher No<input v-model="form.voucherNo" maxlength="100" placeholder="Auto-generated if blank"></label><label>Debit Account<select v-model="form.debitAccountCode" required><option value="" disabled>Select account</option><option v-for="account in accountOptions" :key="`debit-${account.code}`" :value="account.code">{{ accountLabel(account.code) }}</option></select></label><label>Credit Account<select v-model="form.creditAccountCode" required><option value="" disabled>Select account</option><option v-for="account in accountOptions" :key="`credit-${account.code}`" :value="account.code">{{ accountLabel(account.code) }}</option></select></label><label>Amount (Rs)<input v-model.number="form.amount" type="number" min="0.01" step="0.01" required></label><label>Reference<input v-model="form.reference" maxlength="100"></label><label class="wide">Particulars<input v-model="form.particulars" maxlength="1000" required></label><label class="wide">Remarks<textarea v-model="form.remarks" maxlength="1000"></textarea></label><div class="form-actions"><span v-if="message" class="success">{{ message }}</span><span v-if="error" class="error">{{ error }}</span><button :disabled="submitting">{{ submitting ? 'Posting…' : 'Post Journal' }}</button></div></form>
    <div class="card table"><table><thead><tr><th>Date</th><th>Journal No</th><th>Voucher No</th><th>Account Head</th><th>Particulars</th><th>Debit (Rs)</th><th>Credit (Rs)</th><th>Reference</th><th>Posted to Ledger (Y/N)</th><th>Entered By</th><th>Approved By</th><th>Remarks</th></tr></thead><tbody><tr v-for="row in rows || []" :key="row.id"><td>{{ row.entryDate }}</td><td>{{ journalNo(row.reference || '') }}</td><td>{{ journalNo(row.reference || '') }}</td><td>{{ row.accountHead }} ({{ row.accountCode }})</td><td>{{ row.particulars || '—' }}</td><td>{{ Number(row.debit) ? fmt(row.debit) : '—' }}</td><td>{{ Number(row.credit) ? fmt(row.credit) : '—' }}</td><td>{{ row.reference || '—' }}</td><td>Y</td><td>{{ row.enteredBy || '—' }}</td><td>{{ row.approvedBy || '—' }}</td><td>{{ row.remarks || '—' }}</td></tr><tr v-if="!rows?.length"><td colspan="12" class="empty">No journal entries posted.</td></tr></tbody></table></div>
  </main>
</template>
<style scoped>main{max-width:100%}.heading{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}h1{font-size:20px;margin:0 0 4px}.heading p{margin:0;color:var(--color-text-muted);font-size:13px}.link-button,button{display:inline-block;padding:8px 12px;background:var(--color-accent);color:#fff;border:0;border-radius:5px;text-decoration:none;cursor:pointer}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.form h2{grid-column:1/-1;font-size:15px;margin:0}label{font-size:12px}input,select,textarea{display:block;width:100%;padding:8px;margin-top:4px;border:1px solid var(--color-border);border-radius:5px;background:var(--color-surface)}textarea{min-height:65px;resize:vertical}.wide{grid-column:span 2}.form-actions{grid-column:1/-1;display:flex;align-items:center;gap:12px}.success{color:var(--color-accent)}.error{color:var(--color-danger)}.table{overflow:auto;margin-top:16px}table{min-width:1450px;width:100%;border-collapse:collapse}th,td{padding:8px;text-align:left;white-space:nowrap;border-bottom:1px solid var(--color-border)}th{font-size:12px}.empty{text-align:center;padding:24px;color:var(--color-text-muted)}</style>
