<script setup lang="ts">
interface StockRow { id: string; code: string; name: string; category: string | null; unit: string | null; reorderLevel: string; costPrice: string | null; sellingPrice: string | null; lastMovementDate: string | null; openingStock: number; stockIn: number; stockOut: number; damaged: number; currentStock: number; stockValue: number; warehouse: string; supplierName: string | null; status: string; remarks: string | null }
const { data: stock, refresh } = await useFetch<StockRow[]>('/api/inventory')
const showProductForm = ref(false)
const productSubmitting = ref(false)
const productError = ref('')
const productForm = reactive({ name: '', category: '', unit: '', reorderLevel: 0, costPrice: 0, sellingPrice: 0 })
const showAdjustForm = ref(false)
const adjustSubmitting = ref(false)
const adjustError = ref('')
const adjustForm = reactive({ productId: '', adjustmentDate: new Date().toISOString().slice(0, 10), reason: 'opening' as 'opening' | 'damage' | 'correction', quantity: 0, warehouse: 'Main', remarks: '' })
function fmt(value: number | string) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value)) }
async function submitProduct() {
  productError.value = ''; productSubmitting.value = true
  try { await $fetch('/api/products', { method: 'POST', body: { ...productForm } }); showProductForm.value = false; Object.assign(productForm, { name: '', category: '', unit: '', reorderLevel: 0, costPrice: 0, sellingPrice: 0 }); await refresh() }
  catch (error: any) { productError.value = error?.data?.statusMessage || 'Could not save product' }
  finally { productSubmitting.value = false }
}
async function submitAdjustment() {
  adjustError.value = ''; adjustSubmitting.value = true
  try { await $fetch('/api/inventory/adjust', { method: 'POST', body: { ...adjustForm } }); showAdjustForm.value = false; adjustForm.quantity = 0; adjustForm.warehouse = 'Main'; adjustForm.remarks = ''; await refresh() }
  catch (error: any) { adjustError.value = error?.data?.data?.fieldErrors?.quantity?.[0] || error?.data?.statusMessage || 'Could not save adjustment' }
  finally { adjustSubmitting.value = false }
}
</script>

<template>
  <div>
    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:20px;"><h1 style="font-size:20px; margin:0;">Inventory Registry</h1><div style="display:flex; gap:8px;"><button style="padding:8px 14px; background:white; color:var(--color-accent); border:1px solid var(--color-accent); border-radius:6px; cursor:pointer;" @click="showAdjustForm = !showAdjustForm; showProductForm = false">{{ showAdjustForm ? 'Cancel' : 'Stock Adjustment' }}</button><button style="padding:8px 14px; background:var(--color-accent); color:white; border:none; border-radius:6px; cursor:pointer;" @click="showProductForm = !showProductForm; showAdjustForm = false">{{ showProductForm ? 'Cancel' : '+ New Product' }}</button></div></div>

    <form v-if="showProductForm" class="card" style="margin-bottom:20px; display:grid; grid-template-columns:repeat(3, 1fr); gap:12px;" @submit.prevent="submitProduct"><div><label for="product-name" style="display:block; font-size:12px; margin-bottom:4px;">Product Name</label><input id="product-name" v-model="productForm.name" required style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"></div><div><label for="product-category" style="display:block; font-size:12px; margin-bottom:4px;">Category</label><input id="product-category" v-model="productForm.category" style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"></div><div><label for="product-unit" style="display:block; font-size:12px; margin-bottom:4px;">Unit</label><input id="product-unit" v-model="productForm.unit" placeholder="Kg, Packet, Bottle" style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"></div><div><label for="product-reorder" style="display:block; font-size:12px; margin-bottom:4px;">Reorder Level</label><input id="product-reorder" v-model.number="productForm.reorderLevel" type="number" min="0" style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"></div><div><label for="product-cost" style="display:block; font-size:12px; margin-bottom:4px;">Unit Cost (Rs)</label><input id="product-cost" v-model.number="productForm.costPrice" type="number" min="0" step="0.01" style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"></div><div><label for="product-price" style="display:block; font-size:12px; margin-bottom:4px;">Selling Price (Rs)</label><input id="product-price" v-model.number="productForm.sellingPrice" type="number" min="0" step="0.01" style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"></div><div style="grid-column:span 3;"><div v-if="productError" style="color:var(--color-danger); font-size:13px; margin-bottom:8px;">{{ productError }}</div><button type="submit" :disabled="productSubmitting" style="padding:10px 16px; background:var(--color-accent); color:white; border:none; border-radius:6px; cursor:pointer;">{{ productSubmitting ? 'Saving…' : 'Save Product' }}</button></div></form>

    <form v-if="showAdjustForm" class="card" style="margin-bottom:20px; display:grid; grid-template-columns:repeat(3, 1fr); gap:12px;" @submit.prevent="submitAdjustment"><div><label for="adjust-product" style="display:block; font-size:12px; margin-bottom:4px;">Product</label><select id="adjust-product" v-model="adjustForm.productId" required style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"><option value="" disabled>Select product</option><option v-for="product in stock" :key="product.id" :value="product.id">{{ product.name }} ({{ product.code }}) — {{ product.warehouse }}</option></select></div><div><label for="adjust-date" style="display:block; font-size:12px; margin-bottom:4px;">Date</label><input id="adjust-date" v-model="adjustForm.adjustmentDate" type="date" required style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"></div><div><label for="adjust-reason" style="display:block; font-size:12px; margin-bottom:4px;">Reason</label><select id="adjust-reason" v-model="adjustForm.reason" style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"><option value="opening">Opening Stock</option><option value="damage">Damage / Loss</option><option value="correction">Count Correction</option></select></div><div><label for="adjust-quantity" style="display:block; font-size:12px; margin-bottom:4px;">Quantity</label><input id="adjust-quantity" v-model.number="adjustForm.quantity" type="number" step="0.01" required style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"></div><div><label for="adjust-warehouse" style="display:block; font-size:12px; margin-bottom:4px;">Warehouse</label><input id="adjust-warehouse" v-model="adjustForm.warehouse" required maxlength="100" style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"></div><div><label for="adjust-remarks" style="display:block; font-size:12px; margin-bottom:4px;">Remarks</label><input id="adjust-remarks" v-model="adjustForm.remarks" maxlength="300" style="width:100%; padding:8px; border:1px solid var(--color-border); border-radius:6px;"></div><div style="grid-column:span 3;"><div v-if="adjustError" style="color:var(--color-danger); font-size:13px; margin-bottom:8px;">{{ adjustError }}</div><button type="submit" :disabled="adjustSubmitting" style="padding:10px 16px; background:var(--color-accent); color:white; border:none; border-radius:6px; cursor:pointer;">{{ adjustSubmitting ? 'Saving…' : 'Save Adjustment' }}</button></div></form>

    <div style="overflow-x:auto;"><table style="width:100%; min-width:1850px; border-collapse:collapse;"><thead><tr style="text-align:left; border-bottom:1px solid var(--color-border);"><th style="padding:8px;">Product Code</th><th style="padding:8px;">Date</th><th style="padding:8px;">Product Name</th><th style="padding:8px;">Category</th><th style="padding:8px;">Unit</th><th style="padding:8px;">Opening Stock</th><th style="padding:8px;">Stock In</th><th style="padding:8px;">Stock Out</th><th style="padding:8px;">Damaged</th><th style="padding:8px;">Closing Stock</th><th style="padding:8px;">Reorder Level</th><th style="padding:8px;">Unit Cost (Rs)</th><th style="padding:8px;">Selling Price (Rs)</th><th style="padding:8px;">Stock Value (Rs)</th><th style="padding:8px;">Warehouse</th><th style="padding:8px;">Supplier</th><th style="padding:8px;">Status</th><th style="padding:8px;">Remarks</th></tr></thead><tbody><tr v-for="product in stock" :key="`${product.id}-${product.warehouse}`" style="border-bottom:1px solid var(--color-border);"><td style="padding:8px;">{{ product.code }}</td><td style="padding:8px;">{{ product.lastMovementDate || '—' }}</td><td style="padding:8px;">{{ product.name }}</td><td style="padding:8px;">{{ product.category || '—' }}</td><td style="padding:8px;">{{ product.unit || '—' }}</td><td style="padding:8px;">{{ product.openingStock }}</td><td style="padding:8px;">{{ product.stockIn }}</td><td style="padding:8px;">{{ product.stockOut }}</td><td style="padding:8px;">{{ product.damaged }}</td><td style="padding:8px;">{{ product.currentStock }}</td><td style="padding:8px;">{{ product.reorderLevel }}</td><td style="padding:8px;">{{ fmt(product.costPrice ?? 0) }}</td><td style="padding:8px;">{{ fmt(product.sellingPrice ?? 0) }}</td><td style="padding:8px;">{{ fmt(product.stockValue) }}</td><td style="padding:8px;">{{ product.warehouse }}</td><td style="padding:8px;">{{ product.supplierName || '—' }}</td><td style="padding:8px;"><span :style="{ color: product.status === 'Reorder' ? 'var(--color-danger)' : 'var(--color-text)', fontWeight: product.status === 'Reorder' ? 700 : 400 }">{{ product.status }}</span></td><td style="padding:8px;">{{ product.remarks || '—' }}</td></tr></tbody></table></div>
  </div>
</template>
